# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 50h # SS220-RoleTime
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 5h # SS220-RoleTime 2
    - !type:AgeRequirement
      requiredAge: 20
      ignoreSpecies: [ Ipc ] #SS220-JobsAgeIPC
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
  weight: 10
  startingGear: CMOGear
  experienceDefinition: ChiefMedicalOfficerRoleExperience # SS220-experience
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  radioBold: true
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Paramedic
  - Psychologist #SS220 New_accesses_and_some_tweaks
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    #ears: ClothingHeadsetCMO #SS220HeadsetLoadout
  storage:
    back:
    - Flash
    - FilledSurgeryMedkit # ss220-surgery-update

- type: chameleonOutfit
  id: ChiefMedicalOfficerChameleonOutfit
  job: ChiefMedicalOfficer
# hasMindShield: false #ss220 ChameleonOutfit fix
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
