// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Ghost;

[GenerateTypedNameReferences]
public sealed partial class GhostHudWindow : FancyWindow
{
    public event Action<ProtoId<GhostHudPrototype>, bool>? OnHudToggled;

    public GhostHudWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetState(GhostHudBoundUserInterfaceState state)
    {
        HudList.RemoveAllChildren();

        foreach (var hud in state.Huds)
        {
            var checkbox = new CheckBox
            {
                Text = Loc.GetString(hud.Name),
                Pressed = hud.Enabled,
            };
            checkbox.OnToggled += args => OnHudToggled?.Invoke(hud.Id, args.Pressed);
            HudList.AddChild(checkbox);
        }
    }
}
