- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    #SS220 requirements begin
    # off
    # - !type:DepartmentTimeRequirement
    #   department: Engineering
    #   time: 9000 # 2.5 hours
    # - !type:DepartmentTimeRequirement
    #   department: Medical
    #   time: 9000 # 2.5 hours
    # - !type:DepartmentTimeRequirement
    #   department: Science
    #   time: 9000 # 2.5 hrs
    # - !type:DepartmentTimeRequirement
    #   department: Security
    #   time: 9000 # 2.5 hrs
    # - !type:DepartmentTimeRequirement
    #   department: Command
    #   time: 9000 # 2.5 hours
    # off
    - !type:OverallPlaytimeRequirement
      time: 50h # SS220-RoleTime
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 20h # SS220-RoleTime 2
    - !type:AgeRequirement
      requiredAge: 20
      ignoreSpecies: [ Ipc ] #SS220-JobsAgeIPC
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
    #SS220 requirements end
  weight: 20
  startingGear: HoPGear
  experienceDefinition: HeadOfPersonnelRoleExperience
  icon: "JobIconHeadOfPersonnel"
  supervisors: job-supervisors-captain
  radioBold: true
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer #SS220-Law Department
  - Cargo
  - Atmospherics
  - Medical
  - Paramedic #SS220 PaNfixes
  #SS220 New_accesses_and_some_tweaks start
  - Clown
  - Librarian
  - Psychologist
  - Reporter
  - Mime
  - Musician
  #SS220 New_accesses_and_some_tweaks end
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoPGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    #ears: ClothingHeadsetAltCommand #SS220 Headsetloadout
    belt: BoxFolderClipboardThreePapers
    eyes: ClothingEyesHudCommand
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: HeadOfPersonnelChameleonOutfit
  job: HeadOfPersonnel
# hasMindShield: false #ss220 ChameleonOutfit fix
  equipment:
    head: ClothingHeadHatHopcap
    eyes: ClothingEyesHudCommand
    mask: ClothingMaskNeckGaiterRed
    neck: ClothingNeckCloakHop
    outerClothing: ClothingOuterWinterHoP

