- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    #SS220 requirements begin
    # off
    # - !type:RoleTimeRequirement
    #   role: JobCargoTechnician
    #   time: 18000 #5 hrs
    # - !type:RoleTimeRequirement
    #   role: JobSalvageSpecialist
    #   time: 9000 #2.5 hrs
    # - !type:DepartmentTimeRequirement
    #   department: Cargo
    #   time: 36000 #10 hours
    # off
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 30h # SS220-RoleTime
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 5h # SS220-RoleTime 2
    - !type:OverallPlaytimeRequirement
      time: 50h # SS220-RoleTime
    - !type:AgeRequirement
      requiredAge: 20
      ignoreSpecies: [ Ipc ] #SS220-JobsAgeIPC
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
    #SS220 requirements end
  weight: 10
  startingGear: QuartermasterGear
  experienceDefinition: QuartermasterRoleExperience # SS220-experience
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff


- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
 #ears: ClothingHeadsetQM #SS220 HeadsetLoadout
    belt: BoxFolderClipboardThreePapers
    pocket1: AppraisalTool
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: QuartermasterChameleonOutfit
  job: Quartermaster
# hasMindShield: true #ss220 ChameleonOutfit fix
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
