using Content.Client.Guidebook.Richtext;
using Content.Client.Resources;
using Content.Client.SmartFridge;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Lock;
using Content.Shared.Shuttles.Components;
using Content.Shared.SmartFridge;
using Content.Shared.Solar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console.Commands;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;
using static Content.Shared.Disposal.Components.DisposalUnitComponent;
using static Robust.Client.UserInterface.Controls.BaseButton;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Lock.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class RotaryLockMenu : BaseWindow
    {

        [Dependency] private readonly IEntityManager _entityManager = default!;
        [Dependency] private readonly IResourceCache _resource = default!;

        public event Action<GUIBoundKeyEventArgs, ListData>? OnItemSelected;

        private readonly StyleBoxFlat _styleBox = new() { BackgroundColor = new Color(70, 73, 102) };

        public event Action<int>? OnRotateLeftPressed;
        public event Action<int>? OnRotateRightPressed;

        public event Action? OnOpenPressed;

        private static readonly ResPath TexturePath1 = new ResPath("/Textures/SS220/Interface/Calculator/safe.png");

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            return DragMode.Move;
        }

        public RotaryLockMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Left10.OnPressed += _ => OnRotateLeftPressed?.Invoke(10);
            Left1.OnPressed += _ => OnRotateLeftPressed?.Invoke(1);

            Open.OnPressed += _ => OnOpenPressed?.Invoke();

            Right1.OnPressed += _ => OnRotateRightPressed?.Invoke(1);
            Right10.OnPressed += _ => OnRotateRightPressed?.Invoke(10);

            //VendingContents.SearchBar = SearchBar;
            //SafeContents.DataFilterCondition += DataFilterCondition;
            SafeContents.GenerateItem += GenerateButton;
            SafeContents.ItemKeyBindDown += (args, data) => OnItemSelected?.Invoke(args, data);

            CloseButton.OnPressed += _ => Close();

            var backgroundImage = _resource.GetTexture(TexturePath1);
            //var backgroundImageMode = visuals.BackgroundImageTile ? StyleBoxTexture.StretchMode.Tile : StyleBoxTexture.StretchMode.Stretch;
            var backgroundImageMode = StyleBoxTexture.StretchMode.Stretch;

            Vector2 vec;
            vec.X = 5.0f;
            vec.Y = 5.0f;

            BackgroundPanel.PanelOverride = new StyleBoxTexture
            {
                Texture = backgroundImage,
                TextureScale = vec,
                Mode = backgroundImageMode,
                PatchMarginLeft = 0,
                PatchMarginBottom = 0,
                PatchMarginRight = 0,
                PatchMarginTop = 0
            };

        }
        private bool DataFilterCondition(string filter, ListData data)
        {
            if (data is not SmartFridgeListData entry)
                return false;

            if (string.IsNullOrEmpty(filter))
                return true;

            return entry.Entry.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
        }

        private void GenerateButton(ListData data, ListContainerButton button)
        {
            if (data is not SmartFridgeListData entry)
                return;

            var label = Loc.GetString("smart-fridge-list-item", ("item", entry.Entry.Name), ("amount", entry.Amount));
            button.AddChild(new SmartFridgeItem(entry.Representative, label));

            button.ToolTip = label;
            button.StyleBoxOverride = _styleBox;
        }

        public void Populate(Entity<RotaryLockComponent> ent)
        {
            var listData = new List<ListData>();

            foreach (var item in ent.Comp.Entries)
            {
                if (ent.Comp.ContainedEntries.TryGetValue(item, out var items) && items.Count != 0)
                {
                    var representative = _entityManager.GetEntity(items.First());
                    listData.Add(new SmartFridgeListData(representative, item, items.Count));
                }
            }

            SafeContents.PopulateList(listData);
        }

        public void UpdateState(RotaryLockUiState state)
        {
            // Dial
            RotaryKnob.DialPos = state.DialPos;
            DialPosIndicator.Text = state.DialPos.ToString();

            // State
            switch (state.Status)
            {
                case SafeStatus.OPEN:
                    Left10.Disabled = true;
                    Left1.Disabled = true;
                    Right10.Disabled = true;
                    Right1.Disabled = true;
                    RotaryKnob.Visible = false;
                    DialPosIndicator.Visible = false;
                    SafeContents.Visible = true;
                    Open.Text = "Close";
                    //Open.RemoveStyleClass(StyleNano.StyleClassButtonColorGreen);
                    break;
                case SafeStatus.UNLOCKED:
                    Left10.Disabled = false;
                    Left1.Disabled = false;
                    Open.Disabled = false;
                    Right10.Disabled = false;
                    Right1.Disabled = false;
                    RotaryKnob.Visible = true;
                    DialPosIndicator.Visible = true;
                    SafeContents.Visible = false;
                    Open.Disabled = false;
                    Open.Text = "Open";
                    //Open.AddStyleClass(StyleNano.StyleClassButtonColorGreen);
                    break;
                case SafeStatus.LOCKED:
                    Left10.Disabled = false;
                    Left1.Disabled = false;
                    Open.Disabled = true;
                    Right10.Disabled = false;
                    Right1.Disabled = false;
                    RotaryKnob.Visible = true;
                    DialPosIndicator.Visible = true;
                    SafeContents.Visible = false;
                    Open.Disabled = true;
                    //Open.RemoveStyleClass(StyleNano.StyleClassButtonColorGreen);
                    break;
                case SafeStatus.DESTROYED:
                    break;
            }
        }

        public void Update()
        {
        }
    }

    public sealed class RotaryLockKnob : Control
    {
        [Dependency] private readonly IResourceCache _resource = default!;

        private readonly Texture _knobTexture;
        private static readonly ResPath TexturePath = new ResPath("/Textures/Interface/Misc/safe_dial.png");

        public int DialPos = 0;

        public RotaryLockKnob()
        {
            IoCManager.InjectDependencies(this);
            _knobTexture = _resource.GetTexture(TexturePath);
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            Angle angle = -Angle.FromDegrees(360.0 / 100.0 * DialPos);

            Vector2i pos = new Vector2i(0, _knobTexture.Size.Y / 2);
            handle.SetTransform(GlobalPixelPosition + pos, angle);

            Vector2i pos2 = new Vector2i(_knobTexture.Size.X / 2, _knobTexture.Size.Y / 2);
            //handle.DrawTexture(_knobTexture, -pos2);
        }
    }
}
