// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.SS220.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class AntagonistsWindow : DefaultWindow
    {
        private PlayerInfo? _selectedAntagonist;

        protected override void EnteredTree()
        {
            base.EnteredTree();
            AntagonistsList.OnSelectionChanged += OnListOnOnSelectionChanged;
            ListOfTargetsButton.OnPressed += ListOfTargetsButtonOnPressed;
            AddTargetButton.OnWindowCreated += AddTargetButtonOnWindowCreated;
            CustomObjectivesFilter.OnToggled += OnCustomObjectivesFilterToggled;
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            AntagonistsList.OnSelectionChanged -= OnListOnOnSelectionChanged;
            ListOfTargetsButton.OnPressed -= ListOfTargetsButtonOnPressed;
            AddTargetButton.OnWindowCreated -= AddTargetButtonOnWindowCreated;
            CustomObjectivesFilter.OnToggled -= OnCustomObjectivesFilterToggled;
        }

        private void OnCustomObjectivesFilterToggled(BaseButton.ButtonToggledEventArgs args)
        {
            AntagonistsList.SetCustomObjectivesFilter(args.Pressed);
        }

        private void OnListOnOnSelectionChanged(PlayerInfo? obj)
        {
            _selectedAntagonist = obj;
            var disableButtons = _selectedAntagonist == null;
            ListOfTargetsButton.Disabled = disableButtons;
            AddTargetButton.Disabled = disableButtons;
        }

        private void ListOfTargetsButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            if (_selectedAntagonist == null)
                return;

            IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand(
                $"openobjectives {_selectedAntagonist.SessionId}");
        }

        private void AddTargetButtonOnWindowCreated(DefaultWindow window)
        {
            if (_selectedAntagonist is null)
                return;
            var addObjectiveWindow = (AddObjectiveWindow) window;
            var antagSession = IoCManager.Resolve<IPlayerManager>().GetSessionById(_selectedAntagonist.SessionId);
            addObjectiveWindow.SetAntagonist(antagSession);
        }
    }
}
