using Content.Shared.SS220.Pirates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Pirates;

[GenerateTypedNameReferences]
public sealed partial class PirateLootWindow : DefaultWindow
{
    public event Action? AppraisePressed;
    public event Action? SellPressed;

    public PirateLootWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        AppraiseButton.OnPressed += OnAppraisePressed;
        SellButton.OnPressed += OnSellPressed;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        AppraiseButton.OnPressed -= OnAppraisePressed;
        SellButton.OnPressed -= OnSellPressed;
    }

    public void UpdateState(PirateLootConsoleState state)
    {
        Summary.Text = Loc.GetString("pirate-loot-window-appraisal",
            ("count", state.ItemCount),
            ("value", state.Appraisal));
        ShiftTotal.Text = Loc.GetString("pirate-loot-window-total",
            ("count", state.TotalItemsSold),
            ("value", state.TotalLootValue));
    }

    private void OnAppraisePressed(BaseButton.ButtonEventArgs args)
    {
        AppraisePressed?.Invoke();
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs args)
    {
        SellPressed?.Invoke();
    }
}
