using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Pirates;

[GenerateTypedNameReferences]
public sealed partial class PirateRecruitmentWindow : DefaultWindow
{
    public event Action<bool>? Response;

    public PirateRecruitmentWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        AcceptButton.OnPressed += OnAcceptPressed;
        DeclineButton.OnPressed += OnDeclinePressed;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        AcceptButton.OnPressed -= OnAcceptPressed;
        DeclineButton.OnPressed -= OnDeclinePressed;
    }

    private void OnAcceptPressed(BaseButton.ButtonEventArgs args)
    {
        Response?.Invoke(true);
    }

    private void OnDeclinePressed(BaseButton.ButtonEventArgs args)
    {
        Response?.Invoke(false);
    }
}
