using Content.Client.SS220.Experience;
using Content.Shared.Atmos;
using Content.Shared.Body.Components;
using Content.Shared.Chemistry.Components.SolutionManager;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Damage.Systems;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.SS220.Experience.Skill;
using Content.Shared.SS220.LimitationRevive;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;
namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private readonly RandomShuffle<GetHealthAnalyzerShuffleChance> _randomShuffle = new();  // SS220-experience-update
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly DamageableSystem _damageable;
    private readonly SharedSolutionContainerSystem _solSystem; // ss220 add reagents to health analyzer

    // SS220-experience-update-begin
    /// <summary> This value was chosen for better user experience </summary>
    private const float SkillIssueReshuffleChance = 0.15f;

    private const float TemperatureSkillIssueRandomScaleAmplitude = 0.3f;
    private const float BloodSkillIssueRandomScaleAmplitude = 0.3f;
    private const float DamageSkillIssueRandomScaleAmplitude = 0.3f;

    private const float MaxRandomSkillIssueFlatDamageAddition = 12f;
    private const float MinRandomSkillIssueFlatDamageAddition = 0f;
    // SS220-experience-update-end

    // SS220 clinic death analyzer - start
    private const int WarningThresholdMinutes = 1;
    // SS220 clinic death analyzer - end

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _damageable = _entityManager.System<DamageableSystem>();
        _solSystem = _entityManager.System<SharedSolutionContainerSystem>(); // ss220 add reagents to health analyzer

        _randomShuffle.MakeNewRandomChange(SkillIssueReshuffleChance); // SS220-experience-update
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        PrintButton.Visible = state.CanPrint; // SS220-health-analyzer-report
        PrintButton.Disabled = true; // SS220-health-analyzer-report

        ReagentsContainer.DisposeAllChildren(); // ss220 add reagents to health

        var target = _entityManager.GetEntity(state.TargetEntity);

        if (target == null
            || !_entityManager.TryGetComponent<DamageableComponent>(target, out var damageable))
        {
            NoPatientDataText.Visible = true;
            return;
        }

        PrintButton.Disabled = !state.CanPrint; // SS220-health-analyzer-report

        // ss220 add reagents to health analyzer start
        if (_entityManager.TryGetComponent<SolutionContainerManagerComponent>(target, out var solComp))
        {
            if (_solSystem.TryGetSolution((target.Value, solComp), BloodstreamComponent.DefaultBloodSolutionName, out var solutions))
            {
                foreach (var (reagent, valueReagent) in solutions.Value.Comp.Solution.Contents)
                {
                    if (!_prototypes.TryIndex<ReagentPrototype>(reagent.Prototype, out var reagentPrototype))
                        continue;

                    var title = Loc.GetString("health-analyzer-window-entity-reagent-text",
                        ("reagentName", reagentPrototype.LocalizedName),
                        ("reagentValue", valueReagent));

                    var label = new Label
                    {
                        Text = title,
                        Modulate = reagentPrototype.SubstanceColor,
                    };

                    ReagentsContainer.AddChild(label);
                }
            }
        }

        ReagentsSection.Visible = ReagentsContainer.ChildCount > 0;
        // ss220 add reagents to health analyzer end

        NoPatientDataText.Visible = false;

        // SS220 clinic death analyzer - start
        _entityManager.TryGetComponent<LimitationReviveComponent>(target.Value, out var reviveComp);
        _entityManager.TryGetComponent<MobStateComponent>(target.Value, out var mobStateComponent);

        var clinicalDeathTimeRemaining = SharedLimitationReviveSystem.GetClinicalDeathTimeRemaining(reviveComp, mobStateComponent);

        if (clinicalDeathTimeRemaining is { } timeLeft)
        {
            ClinicalDeathLabel.Visible = true;
            ClinicalDeathTimeLabel.Visible = true;

            if (timeLeft <= TimeSpan.Zero)
            {
                var reviveExhausted = reviveComp != null && reviveComp.DeathCounter >= reviveComp.ReviveLimit;

                ClinicalDeathTimeLabel.Text = Loc.GetString(reviveExhausted
                    ? "health-analyzer-window-clinical-death-expired"
                    : "health-analyzer-window-clinical-death-revivable");
            }
            else
            {
                var decayText = Loc.GetString("health-analyzer-window-clinical-death-decay",
                    ("timeLeft", timeLeft.ToString(@"mm\:ss")));

                var decayColor = timeLeft.TotalMinutes >= WarningThresholdMinutes ? Color.Yellow : Color.Red;

                var decayMsg = new FormattedMessage();
                decayMsg.PushColor(decayColor);
                decayMsg.AddMarkupPermissive(decayText);
                ClinicalDeathTimeLabel.SetMessage(decayMsg);
            }
        }
        else
        {
            ClinicalDeathLabel.Visible = false;
            ClinicalDeathTimeLabel.Visible = false;
        }
        // SS220 clinic death analyzer - end

        // Scan Mode

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        // Patient Information

        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = state.ScanMode.HasValue && state.ScanMode.Value;
        NoDataTex.Visible = !SpriteView.Visible;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidProfileComponent>(target.Value,
                out var humanoidComponent)
                ? Loc.GetString(_prototypes.Index(humanoidComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        // Basic Diagnostic

        // SS220-experience-update-begin
        if (state.Bleeding is not null)
            state.Bleeding = _randomShuffle.GetRandomBool(nameof(state.Bleeding), state.Bleeding.Value);

        state.Temperature = _randomShuffle.GetRandomFromScaleAmplitude(nameof(state.Temperature), state.Temperature, TemperatureSkillIssueRandomScaleAmplitude);
        state.BloodLevel = _randomShuffle.GetRandomFromScaleAmplitude(nameof(state.BloodLevel), state.BloodLevel, BloodSkillIssueRandomScaleAmplitude);
        // SS220-experience-update-end

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? $"{state.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        //SS220 LimitationRevive - start
        DeathLabel.Text = state.CounterDeath != null
            ? $"{state.CounterDeath}"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
        //SS220 LimitationRevive - end

        //SS220 clinic death analyzer - start
        if (mobStateComponent != null)
        {
            StatusLabel.Text = mobStateComponent.CurrentState == MobState.Dead && clinicalDeathTimeRemaining > TimeSpan.Zero
                ? Loc.GetString("health-analyzer-window-entity-clinical-dead-text")
                : GetStatus(mobStateComponent.CurrentState);
        }
        else
        {
            StatusLabel.Text = Loc.GetString("health-analyzer-window-entity-unknown-text");
        }
        //SS220 clinic death analyzer - end

        // Total Damage

        // SS220-experience-update-begin
        var totalDamage = _randomShuffle.GetRandomFromScaleAmplitude(nameof(target), _damageable.GetTotalDamage(target.Value), DamageSkillIssueRandomScaleAmplitude);
        DamageLabel.Text = totalDamage.ToString();
        // SS220-experience-update-end

        // DamageLabel.Text = _damageable.GetTotalDamage(target.Value).ToString(); [wizden-code] ss220-experience-update

        // Alerts

        var showAlerts = state.Unrevivable == true || state.Bleeding == true;

        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        if (state.Bleeding == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        // Damage Groups

        var damageSortedGroups =
            _damageable.GetDamagePerGroup(target.Value)
                .OrderByDescending(damage => damage.Value)
                .ToDictionary(x => x.Key, x => x.Value);

        var damagePerType = _damageable.GetAllDamage(target.Value).DamageDict;

        DrawDiagnosticGroups(damageSortedGroups, damagePerType);
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private void DrawDiagnosticGroups(
        Dictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups,
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        // foreach (var (damageGroupId, damageAmount) in groups) // [wizden] SS220-experience-update
        foreach (var (damageGroupId, startDamageAmount) in groups) // SS220-experience-update
        {
            var damageAmount = _randomShuffle.GetRandomBounded(damageGroupId, startDamageAmount, MinRandomSkillIssueFlatDamageAddition, MaxRandomSkillIssueFlatDamageAddition); // SS220-experience-update
            if (damageAmount == 0)
                continue;

            damageAmount *= _randomShuffle.GetRandomFromScaleAmplitude(damageGroupId, 1f, DamageSkillIssueRandomScaleAmplitude); // SS220-experience-update

            var groupTitleText = $"{Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount)
            )}";

            var groupContainer = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, damageGroupId));

            GroupsContainer.AddChild(groupContainer);

            // Show the damage for each type in that group.
            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                // SS220-experience-update-begin
                // if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0) [wizden]
                //     continue; [wizden]

                if (!damageDict.TryGetValue(type, out var typeAmount))
                    continue;

                typeAmount = _randomShuffle.GetRandomBounded(damageGroupId, typeAmount, MinRandomSkillIssueFlatDamageAddition, MaxRandomSkillIssueFlatDamageAddition);

                if (typeAmount <= 0)
                    continue;
                // SS220-experience-update-end

                typeAmount *= _randomShuffle.GetRandomFromScaleAmplitude(type, 1f, DamageSkillIssueRandomScaleAmplitude); // SS220-experience-update

                var damageString = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName),
                    ("amount", typeAmount)
                );

                groupContainer.AddChild(CreateDiagnosticItemLabel(damageString.Insert(0, " · ")));
            }
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private static Label CreateDiagnosticItemLabel(string text)
    {
        return new Label
        {
            Text = text,
        };
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower())
        });

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));

        return rootContainer;
    }
}
