using Content.Client.Guidebook.Controls;
using Content.Client.UserInterface.ControlExtensions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Guidebook.Controls;

/// <summary>
/// Displays a food processor ingredient and its output.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GuideFoodProcessorEmbed : PanelContainer, ISearchableControl,
    IPrototypeRepresentationControl
{
    public IPrototype? RepresentedPrototype { get; private set; }

    public GuideFoodProcessorEmbed()
    {
        RobustXamlLoader.Load(this);
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideFoodProcessorEmbed(EntityPrototype source, EntityPrototype result, int amount) : this()
    {
        RepresentedPrototype = source;

        SourceIcon.AddChild(new GuideEntityEmbed(source.ID, false, false));
        SourceName.Text = source.Name;

        ResultIcon.AddChild(new GuideEntityEmbed(result.ID, false, false));
        ResultName.Text = result.Name;
        ResultAmount.Text = $"×{amount}";
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }
}
