using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ComputerIFFEbentConsoleWindow : FancyWindow,
    IComputerWindow<ComputerIFFEbentConsoleBoundUserInterfaceState>
{
    public event Action? ActivateStealth;

    public ComputerIFFEbentConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        StealthButton.OnPressed += _ => ActivateStealth?.Invoke();
        UpdateLabels(TimeSpan.Zero, TimeSpan.Zero);
    }

    public void UpdateState(ComputerIFFEbentConsoleBoundUserInterfaceState state)
    {
        UpdateLabels(state.StealthDuration, state.Cooldown);

        if (state.StealthDuration > TimeSpan.Zero || state.Cooldown > TimeSpan.Zero)
        {
            StealthButton.Disabled = true;
            StealthButton.Text = state.StealthDuration > TimeSpan.Zero
                ? Loc.GetString("computer-iff-ebent-console-active")
                : Loc.GetString("computer-iff-ebent-console-cooldown");
        }
        else
        {
            StealthButton.Disabled = false;
            StealthButton.Text = Loc.GetString("computer-iff-ebent-console-activate");
        }
    }

    private void UpdateLabels(TimeSpan stealthDuration, TimeSpan cooldown)
    {
        StealthTimerLabel.Text = Loc.GetString("computer-iff-ebent-console-time", ("seconds", $"{stealthDuration.TotalSeconds:F0}"));
        CooldownTimerLabel.Text = Loc.GetString("computer-iff-ebent-console-cooldown-time", ("seconds", $"{cooldown.TotalSeconds:F0}"));
    }
}
