## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
  - MagazineBoxLightRiflePractice
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
  - MagazineBoxRiflePractice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - MagazineLightRiflePractice
  - MagazineRiflePractice
  - MagazinePistolPractice
  - SpeedLoaderMagnumPractice
  - MagazinePistolSubMachineGunPractice
  - WeaponFlareGunSecurity

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  - MagazineBoxLightRifle
  - MagazineBoxMagnum
  - MagazineBoxPistol
  - MagazineBoxRifle
  - MagazineLightRifle
  - MagazineLightRifleEmpty
  - MagazinePistol
  - MagazinePistolEmpty
  - MagazinePistolSubMachineGun
  - MagazinePistolSubMachineGunEmpty
  - MagazinePistolSubMachineGunTopMounted
  - MagazinePistolSubMachineGunTopMountedEmpty
  - MagazineRifle
  - MagazineRifleEmpty
  - SpeedLoaderMagnum
  - SpeedLoaderMagnumEmpty
  - MagazineBoxAntiMateriel #SS220 WeaponSniperCompact
  #ss220 more recipies begin
  - SpeedLoaderLightRifle
  - MagazineMagnumEmpty
  - MagazineMagnum
  #ss220 more recipies end

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes:
  - Flash
  - Stunbaton
  - CombatKnife
  - RiotShield

## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield
  - ClothingEyesThermalGlassesSecurity #SS220 Thermals
  - ClothingEyesNightVisionSecurity #SS220 Night vision
  - ClothingBackpackHarmpack
  - RiotBulletShield #SS220 Shield rework
  - RiotLaserShield #SS220 Shield rework
  - FieldShieldGenerator #SS220 Energy shield

- type: latheRecipePack
  id: SecurityBoards
  recipes:
  # - ShuttleGunDusterCircuitboard #SS220-Duster-Resprite
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard
  - ShuttleGunMLGSWCircuitboard #SS220-MLGSW-gun-research

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: SecurityExplosives
  recipes:
  - CableDetStack1
  - EmptyDetonator
  - ExplosivePayload
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: SecurityAmmo
  recipes:
  - BoxBeanbag
  - BoxShotgunIncendiary
  - BoxShotgunUranium
  #- BoxShellTranquilizer #SS220-no-tranq
  - MagazineBoxLightRifleIncendiary
  - MagazineBoxLightRifleUranium
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumUranium
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolUranium
  - MagazineBoxRifleIncendiary
  - MagazineBoxRifleUranium
  - MagazineLightRifleIncendiary
  - MagazineLightRifleUranium
  - MagazinePistolIncendiary
  - MagazinePistolUranium
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunUranium
  - MagazineRifleIncendiary
  - MagazineRifleUranium
  - MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumUranium
  - MagazineMagnumIncendiary #ss220 more recipies
  - MagazineMagnumUranium #ss220 more recipies

- type: latheRecipePack
  id: SecurityWeapons
  recipes:
  - WeaponSniperCompact #SS220 WeaponSniperCompact
  - LaserSMGPowerCell #SS220 WeaponLaserSMG
  - WeaponLaserSMG #SS220 WeaponLaserSMG
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon
  - WeaponTemperatureGun
  - WeaponEnergyCrossbow #SS220 Energy Crossbow
  - WeaponTaser #SS220 taserback

- type: latheRecipePack
  id: SecurityDisablers
  recipes:
  - WeaponDisabler
  - WeaponDisablerSMG
